import React from 'react'
import NavBar from '@component/component/NavBar'
import Slider from '@component/component/Slider'
import ValuesCard from '@component/component/ValuesCard'
import ContactForm from '@component/component/ContactForm'
import Footer from '@component/component/Footer'
import LightBulb from '@component/public/lightbulb-o.png'
import Bank from '@component/public/bank.png'
import Balance from '@component/public/balance-scale.png'
import BackgroundImage from '@component/public/bg.jpg'
import AboutBackground from '@component/public/about-bg.jpg'
import Head from 'next/head'

const slides = [
  {
    image: BackgroundImage,
    text: "THIS IS A PLACE WHERE TECHNOLOGY & CREATIVITY FUSED INTO DIGITAL CHEMISTRY",
  },
  {
    image: AboutBackground,
    text: "WE DON'T HAVE THE BEST BUT WE HAVE THE GREATEST TEAM",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavBar />
      </header>
      <main>
        <Slider slides={slides} />
        <section>
          <h2 className='sec-title'>OUR VALUES</h2>
          <div className='values'>
            <ValuesCard class='value-card red pointer' icon={LightBulb} title='INNOVATIVE' text='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime exercitationem dolorem deserunt, unde, eaque ipsa?' />
            <ValuesCard class='value-card green pointer' icon={Bank} title='LOYALTY' text='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit similique eum itaque facere temporibus dolores.' />
            <ValuesCard class='value-card blue' icon={Balance} title='RESPECT' text='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, sit? Tenetur et neque quod incidunt!' />
          </div>
        </section>
        <section>
          <h2 className='sec-title'>CONTACT US</h2>
          <ContactForm />
        </section>
      </main>
      <Footer />
    </>
  )
}
